### ISSUE TITLE
Lower version of DB

### ISSUE THREAD

**Issue by karloian** [catalyst/moodle-paygw_alipay#5]
Good day, Is there a possible way that i could run the plugin in a lower version of Mysql? My current version is 5.6.41.84.1 thanks in advance.

**Comment by danmarsden** [comment]
Hi @karloian - this plugin uses the payment gateway API which was added to Moodle 3.10 and doesn't exist in Moodle 3.9 so you need to be running Moodle 3.10 or higher to use this plugin.

It does look like Moodle 3.10 does require a newer version of MySql than you have as per:
https://docs.moodle.org/dev/Moodle_3.10_release_notes#Database_requirements

Nothing we can do about this in the alipay plugin sorry - hopefully you'll be able to upgrade soon!
