### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by konghao666** [catalyst/moodle-paygw_alipay#6]
I install the plugin on moodle4.0,
but,It doesn't work.
The following information is displayed

 - cURL error 6: Could not resolve host: https (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by danmarsden** [comment]
Hi there, 

What do you have for the "Gateway endpoint" set in your configuration? - is that a correct Alipay url?

If it is a correct url, this typically indicates an issue with the configuration of your webserver - the code uses curl from your webserver to make calls to Alipays API - (not using the browser of the user, but your webserver communicating directly with alpay behind the scenes.)

Your webserver may be behind a firewall, and may not allow outgoing connections, or you may have dns mis-configured on your webserver. Please open up a command line on the webserver and make sure you can make outgoing http connections from the webserver

**Comment by konghao666** [comment]
Hi,
Thank you very much
 the "Gateway endpoint" url is  the "https://openapi.alipay.com/gateway.do",

I delete these character string "https://", it show me :"Exception - Check failed, please check whether the public key setting of Alipay is correct.  "

Sorry, my English is not good
thanks again

**Comment by danmarsden** [comment]
take a look at the screenshot in the readme: it lists "openapi.alipay.com" on it's own without https:// part and also without the "gateway.do" at the end:
https://github.com/catalyst/moodle-paygw_alipay/blob/main/pix/alipayconfigexample.png

Try that and see if it works?

**Comment by danmarsden** [comment]
closing as no response from the reporter - hopefully you got it working!
